### ISSUE TITLE
We want to use this library in Corona SDK

### ISSUE THREAD

**Issue by inforaudio** [tarantool/mqtt#32]
Hello
we want to use this library in Corona sdk, in windows.
We try and in line 32 of init.lua try to charge the local mqtt_driver = require('mqtt.driver').
This file dont exist.
the compilator try to find driver.lua.. and the file is driver.c
What can i do ?

**Comment by dedok** [comment]
Hi,

Well, I'm not sure that this is possible, and we are don't have experience this it.

Probably I can help you, since it could be interesting for us, please contact with me using email: dedok.mad@gmail.com.
