### ISSUE TITLE
Debian buster package is missing

### ISSUE THREAD

**Issue by bazuchan** [tarantool/mqtt#38]
`curl -L https://packagecloud.io/tarantool/2x/debian/dists/stretch/main/binary-amd64/Packages.bz2 | bzcat | grep mqtt`
is there, but
`curl -L https://packagecloud.io/tarantool/2x/debian/dists/buster/main/binary-amd64/Packages.bz2 | bzcat | grep mqtt`
is not.

**Comment by Totktonada** [comment]
It is already resolved in PR #135. See https://packagecloud.io/app/tarantool/2x/search?q=mqtt&filter=all&dist=buster
