### ISSUE TITLE
mqtt doesn't work with rabbitmq

### ISSUE THREAD

**Issue by zloidemon** [tarantool/mqtt#6]
This is not one task, it is list of issues:

- [ ] No errors on connect, it always returns true although it doesn't work
- [ ] No errors on publish/subscribe even NOT connected server
- [ ] No errors on connect with incorrect protocol (for example AMQP)
- [ ] Incorrect subscribe queues, for example I have virtual host /test, with queue test. Try to subscribe it with `:subscribe('/test/test')` will create a new queue instead use correct (looks like: mqtt-subscription-client_idqos0)
- [ ] Publish doesn't work seems related to subscribe issue
- [ ] Example `:publish()` doesn't work (syntax error)

Configuration of rabbitmq:

```
[
  {rabbit, [
    {cluster_nodes, {['rabbit@tt01'], ram}},
    {cluster_partition_handling, ignore},
    {tcp_listen_options,
         [binary,
         {packet,        raw},
         {reuseaddr,     true},
         {backlog,       128},
         {nodelay,       true},
         {exit_on_close, false}]
    },
    {frame_max, 131072},
    {hipe_compile, true},
    {log_levels, [{connection, info}]},
    {default_user, <<"guest">>},
    {default_pass, <<"guest">>}
  ]},
  {kernel, [
    {inet_dist_listen_max, 9105},
    {inet_dist_listen_min, 9100}
  ]},
  {rabbitmq_management, [
    {listener, [
      {port, 15672}
    ]}
  ]},
  {rabbitmq_mqtt, [
    {allow_anonymous,  false},
    {vhost,            "/test"},
    {tcp_listeners, [1883]}
  ]}
].
```

Console commands to configuration mutt and enable web interface to watch on events and etc:

```
rabbitmq-plugins enable rabbitmq_management
rabbitmq-plugins enable rabbitmq_mqtt
```

**Comment by dedok** [comment]
@zloidemon here are examples
https://github.com/tarantool/mqtt/blob/master/test/api.lua#L91
https://github.com/tarantool/mqtt/blob/master/test/api.lua#L106

Also error handling issues were fixed
