### ISSUE TITLE
MQTT eats 100% CPU

### ISSUE THREAD

**Issue by cyanide-burnout** [tarantool/mqtt#7]
local mqtt = require('mqtt')
local connection = mqtt.new("Registry-LastHeard", true)
connection:connect({ host = 'localhost', port = 1883 })

**Comment by dedok** [comment]
Version is 'mosquitto version 1.4.11 (build date Mon, 20 Feb 2017 22:47:27 +0000) starting'

**Comment by cyanide-burnout** [comment]
https://github.com/tarantool/mqtt/blob/master/mqtt/driver.c#L79

**Comment by dedok** [comment]
Fixed

**Comment by dedok** [comment]
The problem was here:
https://github.com/tarantool/mqtt/blob/master/mqtt/driver.c#L97
