### ISSUE TITLE
libmosquitto kills connection if there is no traffic over nat

### ISSUE THREAD

**Issue by akimapilot** [tarantool/mqtt#9]
libmosquitto kills connection if there is no traffic over nat.

env:
tarantool-mqtt/xenial 1.2.2-1 amd64
mosquitto version 1.4.8 (build date Tue, 23 May 2017 22:14:40 +0100)
mosquitto is an MQTT v3.1 broker.

**Comment by cyanide-burnout** [comment]
I guess it due to infinite timeout on read operation here - https://github.com/tarantool/mqtt/blob/master/mqtt/driver.c#L149

**Comment by pjao** [comment]
Any news about this? 

It looks like in some cases it's causing freezes.

**Comment by dedok** [comment]
Hi,

Fixed in: 9f192fa1aa0a4e17858d4b6c903d53d44acc240f

**Comment by dedok** [comment]
Please check the fix, if it does not work then reopen the issue.

Thanks!
